slither:
 joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 40

 joint01_controller:
  type: position_controllers/JointPositionController
  joint: joint01
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint12_controller:
  type: position_controllers/JointPositionController
  joint: joint12
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint23_controller:
  type: position_controllers/JointPositionController
  joint: joint23
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint34_controller:
  type: position_controllers/JointPositionController
  joint: joint34
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint45_controller:
  type: position_controllers/JointPositionController
  joint: joint45
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint56_controller:
  type: position_controllers/JointPositionController
  joint: joint56
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint67_controller:
  type: position_controllers/JointPositionController
  joint: joint67
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint78_controller:
  type: position_controllers/JointPositionController
  joint: joint78
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint89_controller:
  type: position_controllers/JointPositionController
  joint: joint89
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint910_controller:
  type: position_controllers/JointPositionController
  joint: joint910
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1011_controller:
  type: position_controllers/JointPositionController
  joint: joint1011
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1112_controller:
  type: position_controllers/JointPositionController
  joint: joint1112
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1213_controller:
  type: position_controllers/JointPositionController
  joint: joint1213
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1314_controller:
  type: position_controllers/JointPositionController
  joint: joint1314
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1415_controller:
  type: position_controllers/JointPositionController
  joint: joint1415
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1516_controller:
  type: position_controllers/JointPositionController
  joint: joint1516
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1617_controller:
  type: position_controllers/JointPositionController
  joint: joint1617
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1718_controller:
  type: position_controllers/JointPositionController
  joint: joint1718
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1819_controller:
  type: position_controllers/JointPositionController
  joint: joint1819
  pid: {p: 10.0, i: 1.0, d: 0.5}

 joint1920_controller:
  type: position_controllers/JointPositionController
  joint: joint1920
  pid: {p: 10.0, i: 1.0, d: 0.5}
